import {
  getObjectsRequest,
  getObjectsSuccess,
  getObjectsFailure,
  getObjects,
  getCategorysRequest,
  getCategorysSuccess,
  getCategorysFailure,
  getCategorys,
  getMastersRequest,
  getMastersSuccess,
  getMastersFailure,
  getMasters,
  getGallerysRequest,
  getGallerysSuccess,
  getGallerysFailure,
  getGallerysByObjectId,
} from './apiActions';

import {
  logout,
  getTokenRequest,
  getTokenSuccess,
  getTokenFailure,
  getToken,
  refreshRequest,
  refreshSuccess,
  refreshFailure,
  refresh,
  getUserRequest,
  getUserSuccess,
  getUserFailure,
  getUser,
  createUserRequest,
  createUserSuccess,
  createUserFailure,
  createUser,
  createMasterRequest,
  createMasterSuccess,
  createMasterFailure,
  createMaster,
  setUserLocation,
} from './usersActions';

import { toggleVisibility, toggleObjectModal } from './uiStateActions';
import { updateText, updateSelect } from './formActions';

import {
  createObjectRequest,
  createObjectSuccess,
  createObjectFailure,
  createObject,
  getObjectsProfile,
  getObjectsProfileRequest,
  getObjectsProfileSuccess,
  getObjectsProfileFailure,
} from './profilesApiActions';

//----------exports actions---------
export {
  logout,
  getObjectsRequest,
  getObjectsSuccess,
  getObjectsFailure,
  getObjects,
  getCategorysRequest,
  getCategorysSuccess,
  getCategorysFailure,
  getCategorys,
  getMastersRequest,
  getMastersSuccess,
  getMastersFailure,
  getMasters,
  getGallerysRequest,
  getGallerysSuccess,
  getGallerysFailure,
  getGallerysByObjectId,
  getTokenRequest,
  getTokenSuccess,
  getTokenFailure,
  getToken,
  refreshRequest,
  refreshSuccess,
  refreshFailure,
  refresh,
  getUserRequest,
  getUserSuccess,
  getUserFailure,
  getUser,
  createUserRequest,
  createUserSuccess,
  createUserFailure,
  createUser,
  toggleVisibility,
  toggleObjectModal,
  updateText,
  updateSelect,
  createMasterRequest,
  createMasterSuccess,
  createMasterFailure,
  createMaster,
  setUserLocation,
  createObject,
  createObjectRequest,
  createObjectSuccess,
  createObjectFailure,
  getObjectsProfile,
  getObjectsProfileRequest,
  getObjectsProfileSuccess,
  getObjectsProfileFailure,
}
